### PR TITLE
Scrub PHI from error emails

### PR DESCRIPTION
**Pull request by dargueta-work**
@jasminetsai @danielericlee @jiffyclub

### CODE REVIEW

**Comment by jasminetsai** [comment]
This is a substantial modification to a forked version, I'd be a bit worried about keeping this in sync with the actual airflow head later.

@gwax , do you have thoughts on how we should do this?
@dargueta-work , if this is too hard, let's just either 1) Not log exceptions at all in the emails, or 2) Scrub it for everything.

Or, we move to having our own base operator where all failures go through to pagerduty and we cut out email alerts completely.

**Comment by dargueta-work** [comment]
It's mostly just added stuff. I can split the scrubbing functions out into a separate file so we won't have merge conflicts. I think.

**Comment by melgoetz** [comment]
Ugh, this is getting urgent, more PHI just went out in email. If we don't think this can get merged soon, I'd vote for stopping logging exceptions in emails for now.

**Comment by pauljz** [comment]
Remember that while PHI in email notifications is not a really healthy workflow, it's also not a HIPAA breach if it stays in the organization. If anyone benefits from the notifications it's probably better to leave them on.

**Comment by jasminetsai** [comment]
Technically not a breach but I think it's still a bad idea. We are looking
at leaving it in the logs but out of the emails

On Monday, April 11, 2016, Paul Zumbrun notifications@github.com wrote:

> Remember that while PHI in email notifications is not a really healthy
> workflow, it's also not a HIPAA breach if it stays in the organization. If
> anyone benefits from the notifications it's probably better to leave them
> on.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/CloverHealth/airflow/pull/3#issuecomment-208406194

## 

Jasmine Y. Tsai
+1 415 812 2219

**Comment by dargueta-work** [comment]
Killing this as per Marco's request.

**Pull request closed without merging**
